<!DOCTYPE html>
<html  >
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v4.10.15, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="frontend/assets/images/logo2.png" type="image/x-icon">
    <meta name="description" content="">
    <title>WEBSITE PAFI PUSAT ,  Pengurus Cabang Persatuan Ahli Farmasi Indonesia Kota Jakarta Timur</title>
    <link rel="canonical" href="https://pafijaktimkota.org/" />
    <link rel="stylesheet" href="frontend/assets/web/assets/mobirise-icons-bold/mobirise-icons-bold.css">
    <link rel="stylesheet" href="frontend/assets/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="frontend/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="frontend/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="frontend/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="frontend/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="frontend/assets/animatecss/animate.min.css">
    <link rel="stylesheet" href="frontend/assets/tether/tether.min.css">
    <link rel="stylesheet" href="frontend/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="frontend/assets/theme/css/style.css">
    <link rel="stylesheet" href="frontend/assets/gallery/style.css">
    <link rel="preload" as="style" href="frontend/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="frontend/assets/mobirise/css/mbr-additional.css" type="text/css">
    
		<link rel="stylesheet" href="cdn/css/alertify/alertify.core.css" />
		<link rel="stylesheet" href="cdn/css/datepicker.css" />
		<link rel="stylesheet" href="cdn/css/alertify/alertify.default.css" id="toggleCSS" />
		<link rel="stylesheet" href="cdn/css/Typeahead-BS3-css.css" id="toggleCSS" />
		<link rel="stylesheet" href="cdn/boots/dist/css/bootstrap-timepicker.min.css" />
		<link href="../file.myfontastic.com/n6vo44Re5QaWo8oCKShBs7/icons.css" rel="stylesheet">
		<link rel="stylesheet" href="cdn/css/bootstrap-combined.min.css" id="toggleCSS" />
    
    <script type="text/javascript" src="ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.html"></script>
    <script type="text/javascript" src="cdn/js/jquery.min.js"></script>
  </head>
  <body>
  <style>
  a:link {
    color: red;
  }
  a:visited {
  color: green;
  }
  </style>
    <section class="menu cid-rE0Gn8TeVf" once="menu" id="menu2-49">
      <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <div class="hamburger">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
  </button>
  <div class="menu-logo">
    <div class="navbar-brand">
      <span class="navbar-logo">
      <a href="https://pafijaktimkota.org/#">
      <img src="frontend/assets/images/logo2.png" alt="Mobirise" style="height: 5rem;">
      </a>
      </span>
      <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-4" href="https://pafijaktimkota.org/">
      PAFI
      </a></span>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
      <li class="nav-item">
        <a class="nav-link link text-primary display-7" href="https://pafijaktimkota.org/"><span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link link text-primary dropdown-toggle display-7" href="https://pafijaktimkota.org/" data-toggle="dropdown-submenu" aria-expanded="false"><span class="mbri-edit mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Tentang Kami</a>
        <div class="dropdown-menu">
        <a class="text-primary dropdown-item display-7" href="profil_pafi/">        <span class="mbri-question mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Profil PAFI&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
        <a class="text-primary dropdown-item display-7" href="struktur_organisasi/"><span class="mbri-browse mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Struktur Organisasi&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>

				<a class="text-primary dropdown-item display-7" href="bantuan/"><span class="mbri-browse mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Pusat Bantuan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link link text-primary dropdown-toggle display-7" href="https://pafijaktimkota.org/" data-toggle="dropdown-submenu" aria-expanded="false"><span class="mbri-touch mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Informasi</a>
        <div class="dropdown-menu">
				
					<a class="text-primary dropdown-item display-7" target="_blank" href="https://pafi.or.id/rekapitulasi" style="text-align:left;"><span class="mbri-bookmark mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Rekap Keanggotaan Nsional</a>
          <a class="text-primary dropdown-item display-7" href="regulasi/" style="text-align:left;"><span class="mbri-bookmark mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Regulasi&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
          <a class="text-primary dropdown-item display-7" href="berita/" style="text-align:left;"><span class="mbri-bookmark mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Berita&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
          <a class="text-primary dropdown-item display-7" href="seminar/" style="text-align:left;"><span class="mbri-opened-folder mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Seminar&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
          <a class="text-primary dropdown-item display-7" href="lowongan/" style="text-align:left;"><span class="mbri-calendar mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Loker&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>          
          <a class="text-primary dropdown-item display-7" href="sarat_rekom_str/" style="text-align:left;"><span class="mbri-calendar mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Syarat Rekom STRTTK&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>          
          <a class="text-primary dropdown-item display-7" href="sarat_rekom_sik/" style="text-align:left;"><span class="mbri-calendar mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Syarat Rekom SIP/SIK TTK</a>          
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link link text-primary display-7" href="merchandise/"><span class="mbri-gift mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Merchandise</a>
      </li>
      
        <li class="nav-item dropdown open">
          <a class="nav-link link text-primary dropdown-toggle display-7" href="https://pafijaktimkota.org/" data-toggle="dropdown-submenu" aria-expanded="true"><span class="mbri-users mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Anggota</a>
          <div class="dropdown-menu">
          <a class="text-primary dropdown-item display-7" href="login/"><span class="mbri-key mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Login Anggota</a>
          <a class="text-primary dropdown-item display-7" href="registrasi/"><span class="mbri-edit mbr-iconfont mbr-iconfont-btn"></span>&nbsp;Registrasi &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</a>
          </div>
        </li>
            </ul>
  </div>
</nav>    </section>
    <br/>
    <br/>
    <br/>
    <section class="mbr-section content4 cid-rDXjpKjzbP" id="content4-2j">
  <div class="container">
    <div class="media-container-row">
      <div class="title col-12 col-md-8">
        <h2 class="align-center pb-3 mbr-fonts-style display-2"><strong><br/>WEB PAFI TERINTEGRASI</strong>
        </h2>
      </div>
    </div>
  </div>
</section>
<section class="carousel slide cid-rDXLRDrQGm" data-interval="false" id="slider2-32">
  <div class="container content-slider">
    <div class="content-slider-wrap">
      <div>
        <div class="mbr-slider slide carousel" data-pause="true" data-keyboard="false" data-ride="false" data-interval="false">
          <ol class="carousel-indicators">
            <li data-app-prevent-settings="" data-target="#slider2-32" data-slide-to="0"></li>
            <li data-app-prevent-settings="" data-target="#slider2-32" data-slide-to="1"></li>
            <li data-app-prevent-settings="" data-target="#slider2-32" class=" active" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            
                <div class="carousel-item slider-fullscreen-image active" data-bg-video-slide="false" style="background-image: url(media/bgktan.jpg);">
                  <div class="container container-slide">
                    <div class="image_wrapper">
                      <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(44, 17, 234);"></div>
                      <img src="media/bgktan.jpg">
                      <div class="carousel-caption justify-content-center">
                        <div class="col-10 align-left">
                          <h2 class="mbr-fonts-style display-2">PAFI PUSAT</h2>
                          <a style="color:red;" href="https://pafijaktimkota.org/">pafijaktimkota.org</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                    <div class="carousel-item slider-fullscreen-image" data-bg-video-slide="false" style="background-image: url(media/bgktan.jpg);">
        <div class="container container-slide">
            <div class="image_wrapper">
                <div class="mbr-overlay" style="opacity: 0.8; background-color: rgb(58, 41, 234);"></div>
                <img src="media/bgktan.jpg">
                <div class="carousel-caption justify-content-center">
                    <div class="col-10 align-left">
                        <div style="height:500px; overflow:scroll;">
                            <h2 class="mbr-fonts-style display-2">WEB PAFI TERINTEGRASI</h2>
							PD: 
                            <ul>
                                <li>KOTA JAKARTA TIMUR <a style="color: red;" href="https://pafijaktimkota.org/">pafijaktimkota.org</a></li>
                                <li>KOTA JAKARTA BARAT <a style="color: red;" href="https://pafijakbarkota.org/">pafijakbarkota.org</a></li>
                                <li>KOTA JAKARTA SELATAN <a style="color: red;" href="https://pafijakselkota.org/">pafijakselkota.org</a></li>
                                <li>KOTA PRABUMULIH <a style="color: red;" href="https://pafijakselkota.org/">pafijakselkota.org</a></li>
                                <li>DAERAH ISTIMEWA YOGYAKARTA <a style="color: red;" href="https://pafidiyjogja.org/">pafidiyjogja.org</a></li>
                                <li>KOTA BEKASI <a style="color: red;" href="https://pafibekasikota.org/">pafibekasikota.org</a></li>
                                <li>PROVINSI KEPULAUAN BANGKA BELITUNG <a style="color: red;" href="https://pafikepbelitung.org/">pafikepbelitung.org</a> / <a style="color:red;" href="https://pafiprovbabel.org/">pafiprovbabel.org</a></li>
                                <li>PROVINSI GORONTALO <a style="color: red;" href="https://pafigorontaloprov.org/">pafigorontaloprov.org</a></li>
                                <li>PEMERINTAH KOTA TANGERANG <a style="color: red;" href="https://pafipemkotanggerang.org/">pafipemkotanggerang.org</a></li>
                                <li>PEMERINTAH KOTA SIANTAR <a style="color: red;" href="https://pafipemkosiantar.org/">pafipemkosiantar.org</a></li>
                                <li>PEMERINTAH KOTA LAMONGAN <a style="color: red;" href="https://pafipemkolamongan.org/">pafipemkolamongan.org</a></li>
                                <li>PEMERINTAH KOTA JEMBER <a style="color: red;" href="https://pafipemkojember.org/">pafipemkojember.org/</a></li>
                                <li>PULAU BIDADARI, JAKARTA <a style="color: red;" href="https://pafipulaubidadari.org/">pafipulaubidadari.org</a></li>
                                <li>KEPULAUAN KARIMUN JAWA <a style="color: red;" href="https://pafikepkarimunjawa.org/">pafikepkarimunjawa.org</a></li>
                                <li>KOTA TANJUNG BALAI <a style="color: red;" href="https://sipafikottanjungbalai.org/">sipafikottanjungbalai.org</a></li>
                                </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
                            </div>
          <a data-app-prevent-settings="" class="carousel-control carousel-control-prev" role="button" data-slide="prev" href="#slider2-32"><span aria-hidden="true" class="mbri-left mbr-iconfont"></span><span class="sr-only">Previous</span></a><a data-app-prevent-settings="" class="carousel-control carousel-control-next" role="button" data-slide="next" href="#slider2-32"><span aria-hidden="true" class="mbri-right mbr-iconfont"></span><span class="sr-only">Next</span></a>
        </div>
      </div>
    </div>
  </div>
</section>
      <section class="cid-rE0GnnU63p" id="footer1-4c">
      <div class="container">
        <div class="media-container-row content text-white">
  <div class="col-12 col-md-3">
    <div class="media-wrap">
      <a href="https://pafijaktimkota.org/#">
      <img src="frontend/assets/images/logo2.png" alt="Mobirise">
      </a>
    </div>
  </div>
  <div class="col-12 col-md-3 mbr-fonts-style display-7">
    <h5 class="pb-3">
      Alamat
    </h5>
    <p class="mbr-text">
      Johar Baru, Kec. Johar Baru, Kolaka utara,<br>Daerah Khusus<br>Ibukota Jakarta</p>
  </div>
  <div class="col-12 col-md-3 mbr-fonts-style display-7">
    <h5 class="pb-3">
      Kontak
    </h5>
    <p class="mbr-text">
      Email: admin@pafijaktimkota.org      <br>Telp: 021  4211186<br>Fax: 021  4211794<br>      </p>
  </div>
  <div class="col-12 col-md-3 mbr-fonts-style display-7">
    <h5 class="pb-3">Link</h5>
    <p class="mbr-text">
        <a target="_blank" class="text-primary" href="https://pafikepbelitung.org/">pafikepbelitung.org</a><br/><a target="_blank" class="text-primary" href="https://pafidiyjogja.org/">pafidiyjogja.org</a><br/><a target="_blank" class="text-primary" href="https://pafijakbarkota.org/">pafijakbarkota.org</a><br/><a target="_blank" class="text-primary" href="https://pafijakselkota.org/">pafijakselkota.org</a><br/><a target="_blank" class="text-primary" href="https://pafiprovbabel.org/">pafiprovbabel.org</a><br/><br>
     <p><a style="color:red; font-weight:bold;" href="dataweb/">Lihat link lengkap</a></p>    </p>
  </div>
</div>
		        <div class="footer-lower">
          <div class="media-container-row">
            <div class="col-sm-12">
              <hr>
            </div>
          </div>
          <div class="media-container-row mbr-white">
            <div class="col-sm-6 copyright">
              <p class="mbr-text mbr-fonts-style display-7">
                © Copyright 2023 PAFI - All Rights Reserved
                <br />Powered By: www.kidi.co.id
              </p>
            </div>
            <div class="col-md-6">
  <div class="social-list align-right">
    <div class="soc-item">
      <a href="#" target="_blank">
      <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
      </a>
    </div>
    <div class="soc-item">
      <a href="#" target="_blank">
      <span class="socicon-facebook socicon mbr-iconfont mbr-iconfont-social"></span>
      </a>
    </div>
    <div class="soc-item">
      <a href="#" target="_blank">
      <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
      </a>
    </div>
  </div>
</div>          </div>
        </div>
      </div>
    </section>
    
    <script data-cfasync="false" src="cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script type="text/javascript" src="frontend/assets/web/assets/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="frontend/assets/popper/popper.min.js"></script>
    <script type="text/javascript" src="frontend/assets/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="frontend/assets/smoothscroll/smooth-scroll.js"></script>
    <script type="text/javascript" src="frontend/assets/dropdown/js/nav-dropdown.js"></script>
    <script type="text/javascript" src="frontend/assets/dropdown/js/navbar-dropdown.js"></script>
    <script type="text/javascript" src="frontend/assets/touchswipe/jquery.touch-swipe.min.js"></script>
    <script type="text/javascript" src="frontend/assets/tether/tether.min.js"></script>
    <script type="text/javascript" src="frontend/assets/masonry/masonry.pkgd.min.js"></script>
    <script type="text/javascript" src="frontend/assets/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script type="text/javascript" src="frontend/assets/bootstrapcarouselswipe/bootstrap-carousel-swipe.js"></script>
    <script type="text/javascript" src="frontend/assets/vimeoplayer/jquery.mb.vimeo_player.js"></script>
    <script type="text/javascript" src="frontend/assets/viewportchecker/jquery.viewportchecker.js"></script>
    <script type="text/javascript" src="frontend/assets/theme/js/script.js"></script>
    <script type="text/javascript" src="frontend/assets/slidervideo/script.js"></script>
    <script type="text/javascript" src="frontend/assets/gallery/player.min.js"></script>
    <script type="text/javascript" src="frontend/assets/gallery/script.js"></script>
    <!-- daterangepicker -->
    <script type="text/javascript" src="cdn/boots/plugins/daterangepicker/daterangepicker.js" ></script>
		<script type="text/javascript" src="cdn/js/bootstrap-datepicker.js" ></script>
		<script type="text/javascript" src="cdn/js/jquery.form.js"></script>
		<script type="text/javascript" src="cdn/boots/plugins/timepicker/bootstrap-timepicker.min.js" ></script>
    <script type="text/javascript" src="cdn/boots/dist/js/moment-with-locales.js"></script>
    <script type="text/javascript" src="cdn/boots/dist/js/bootstrap-datetimepicker.js"></script>
    <!-- InputMask -->
    <script type="text/javascript" src="cdn/js/plugins/input-mask/jquery.inputmask.js"></script>
    <script type="text/javascript" src="cdn/js/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script type="text/javascript" src="cdn/js/plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <script>
      $(function () {
        $("[data-mask]").inputmask();
      });
    </script>
		<!-- Start editor-->
		<script type="text/javascript" src="cdn/assets/plugins/ckeditor/ckeditor.js"></script>
		<script type="text/javascript" src="cdn/assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.js"></script>
    
    <input name="animation" type="hidden">
    <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
  <script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'926b998de9ed8548',t:'MTc0MzA0NDAzMS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='cdn-cgi/challenge-platform/h/b/scripts/jsd/708f7a809116/maind41d.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>

</html>
